### ISSUE TITLE
Data of the report is not updated

### ISSUE THREAD

**Issue by toushin-taishi** [mhertzfeld/CrystalReportsNinja#10]
Hi. Is it possible to refresh the data before exporting? RPTs which parameters are programmatically set (needs refresh in crystal report viewers) are yielding outdated data when ran with CrystalReportNinja. Any thoughts about this highly appreciated.

**Comment by mhertzfeld** [comment]
Can you describe what you are doing to set your parameters within the Crystal Reports, programmatically.

I have been pondering adding the ability to execute Ninja with Powershell.  Where instead of passing parameters through the command line you can set progamically using powershell.  This may benefit you since, instead of running your logic through crystal to set your parameters, you could run the logic through powershell and set the results to variables which you could then use to set the parameters.

You can kinda do that already in powershell with the current version of Ninja, but I'm going to clean it up and make it more straight forward.

**Comment by toushin-taishi** [comment]
Hi, sorry for the late reply.
Worked around the issue by modifying the crystal report itself. What I did was disable the option to save the data with crystal and set the parameters within the report itself. I think the problem was the crystal report has the option enabled that saves the data in the 1st place.

**Comment by mhertzfeld** [comment]
The option to save the data in the crystal report should always be off when using ninja.

You can use ninja to set the parameters, you shouldn't have to save them in the crystal reports file.  There is an example of how to pass parameters into the crystal with ninja in the readme.

Good luck.  Post again if you need help.
