### ISSUE TITLE
Database logon failed - (0x8004100F)

### ISSUE THREAD

**Issue by jareddalessandro** [mhertzfeld/CrystalReportsNinja#27]
When I attempt to call the application from Powershell I get a Database Logon failed exception, System.Runtime.InteropServices.COMException (0x8004100F). I'm trying to run the report from Powershell as if from the command line; I'm providing the path to the .exe and .rpt, providing a parameter then running:
_& $crystalNinjaPath @('-F', $RPT, '-O', $reportOutput, '-A', "RunDate:$dateParam", '-LC')_

The only time this works is when I first open the report in Crystal and run it with the same day parameter that will be used in PowerShell with the Save Data with Report toggled on, and run the PowerShell script. Otherwise, it fails, giving the exception mentioned above, when I don't have the Save Data with Report toggled, or if I previously ran it in Crystal with a different day chosen as a parameter. I have tried passing credentials in the script and specifying the server and database and every permutation, but it seems to not be reading or using them. 
I am using the 32-bit .exe with the 32-bit runtime installed version 13.0.25, and using a 32-bit ODBC to connect to an Oracle database.

**Comment by mhertzfeld** [comment]
How are you authenticating with the database?  Are you using Integrated Security?

Under what user account are you manually running the Crystal Report?  Does it prompt for credentials when you run the report manually?

Under what user account are you executing the command as in PowerShell?

Have you tried running this using the command prompt instead of PowerShell?

Please see the PowerShell portion of the instructions to see how I would call Ninja using PowerShell.  Please note the powershell functionality is fairly new and not well tested.

**Comment by mhertzfeld** [comment]
No response for a few months.  Closing.
