### ISSUE TITLE
Failed to open the connection.

### ISSUE THREAD

**Issue by c-josewski** [mhertzfeld/CrystalReportsNinja#34]
I have been trying for days to get this to work and I finally made some progress today. There is something I am missing to make this work as expected though. I have Crystal Reports 2016 (v14.2) running on the development computer and running crystalreportsninja on a different computer.
As for the details:
Downloaded CrystalReportsNinja v1.8.0.0
Downloaded "SAP Crystal Reports for Visual Studio (SP28) runtime (32-bit)" from the first link you provided in the PreRequisites.

The problem:
I have simple report that when I enter a serial number (as shown in cmd line below) that it will grab a model number from the database (using pgAdmin with an ODBC connection). Everything works fine in the Crystal reports software. When I run the command line statement:

"C:\Crystal Reports\downloads\CRN v1.8.0.0.x86\CrystalReportsNinja.exe" -F "C:\Crystal Reports\downloads\CRN v1.8.0.0.x86\Print Trial.rpt" -O "C:\Crystal Reports\Output\test4.pdf" -E pdf -a "serial_number:20090246" -l

I get a failed to open connection message. This only happens when I try and change the serial number. I have tried this multiple different ways.
(1) The report (.rpt file) has a checkbox that says "Save Data with Report". When I do this as long as I enter the serial number that was saved it works fine and creates the report. When I change the serial number, I get the "failed to open the connection" message.
(2) I have tried having the report in its own folder and tried it in the same folder as the CrystalReportsNinja.exe file with identical results.
(3) I have unchecked the "Save Data with Report" and saved a new version of the .rpt file and every time I run the command I get the failed to open connection message.
(4) Added the database name, user and password to the command line prompt. That also fails to open connection.

If there is anything that you can suggest changing on my end or something that I may have done incorrectly please let me know. I have included the log file from one that fails.

[ninja-20200914154507.log](https://github.com/mhertzfeld/CrystalReportsNinja/files/5221345/ninja-20200914154507.log)

**Comment by mhertzfeld** [comment]
I will look into this further tomorrow but if you can give me some details on the questions below it will help.

Always make sure that the option to save data in the report is disabled.  I see that you already did that and got different results when using the "working serial number" on a report where the data was not saved.  Just want to emphasize since having the data save in the report makes troubleshooting more of a pain, as you experienced. 

Are you using a Postgre database?  Guessing since you mentioned pgAdmin.  I have not yet used or tested on Postgre.  

Since you are using the 32bit version of Ninja, make sure you are also using a 32bit ODBC DSN.

Are you setting up your ODBC DSN using the Windows ODBC Data Sources?  Can you double check to ensure the ODBC DSN is identical between the computer with ninja and the computer with Crystal developer (settings, version, ect...).  In the ODBC DSN setup, is there an option to check the connection?  If so does checking the connection succeed on the computer where ninja is installed?

Does your ODBC DSN have the credentials saved?  Are you using some type of Integrated Authentication within the ODBC (I know you can do that with SQL and AD not sure if that's an option with postgre)?

When you run the report with crystal developer, does it prompt for your credentials?

When you "Added the database name, user and password to the command line prompt. That also fails to open connection." did you add the server name as well?  Did you get the same error when passing the server\database\user\password?  As long as the database and server as the same as saved in your crystal report you can probably get away with just passing the user and password.

**Comment by c-josewski** [comment]
I ended up getting this working as desired based off the questions you asked. Turns out I was missing the ODBC driver on the computer with the ninja program. I never thought to even check that since I have been running the database on that machine for years. I appreciate the effort you put forth responding to my problem. Thank you!
